### ISSUE TITLE
Ranger engine not outputting verbose messages

### ISSUE THREAD

**Issue by jxu** [tidymodels/parsnip#1004]
You need a large dataset for this (not sure which built-in datasets are large enough). The ranger fit should produce progress messages like 
```
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
```
However, parsnip fit doesn't show progress, even with verbosity=2 setting.
```
rf_mod <- rand_forest(mode="classification") %>%
  set_engine("ranger") 
rf_fit <- rf_mod %>% 
  fit(price ~ ., data=train,
      control=control_parsnip(verbosity=2, catch=F))
```

**Comment by jxu** [comment]
I got verbose output to show up with `set_engine("ranger", verbose=T, num.threads=32)`. 
Also parsnip seems to default to 1 thread even though ranger defaults to number of CPUs. Does it change the defaults?

**Comment by EmilHvitfeldt** [comment]
With regards to the progress bar. That is happening because the `verbose` argument has been defaulted to be `FALSE`:

https://github.com/tidymodels/parsnip/blob/907d2164a093f10cbbc1921e4b73264ca4053f6b/R/rand_forest_data.R#L119-L135

You can overwrite it by setting `verbose = TRUE` in `set_engine()` as you have seen.

```r
rf_mod <- rand_forest(mode = "classification") %>%
  set_engine("ranger", verbose = TRUE) 
```

With regards to the choice of `num.threads = 1`. We strongly believe that code should run single threaded by default, with an easy way to opt into multi threaded calculations. This stops a number of problems from happening:

- grabbing all 1000 cores of a supercomputer is properly not ideal, but will happen when code defaults to all available cores
- when fitting multiple models in parallel, which is often done in tidymodels when you do hyperparameter tuning, you generally want to fit one model in each thread. If each of those models tries to use all cores you run into issues as well. Hence the default of `num.threads = 1`.

**Comment by jxu** [comment]
Ok, thanks for the info.

**Comment by jxu** [comment]
I think verbose default should be set to true. Tidyverse functions (ex. read_csv) print a lot of progress output anyway.
