### ISSUE TITLE
have predict() load required packages

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#308]
We check for installed packages when fitting a model and attach them. The same should occur when using `predict()`.

**Comment by blairj09** [comment]
This also presents a challenge when models are bundled and referenced in content deployed to RStudio Connect. Since the packages required for the model aren't explicit dependencies (even if they are autoloader with `predict()`) they won't be made available to the RStudio Connect environment.

A current workaround is to manually specify the dependency (ie `library(ranger)`) in the content being published. This may be the preferred route, but it would be nice if there was some way to expose these dependencies automatically when parsnip objects are included in content deployed to RStudio Connect.

**Comment by juliasilge** [comment]
Similar issues may arise when we work on model monitoring + updating + organization, I expect.

**Comment by topepo** [comment]
The merged PR will check for installs and load them when `predict()` is used. `reg_pkg()` is new and will list the packages (besides `parsnip`) required for prediction. This assumes that a recipe was not used (but we can extend it to work with recipes and workflows if needed).
