### ISSUE TITLE
New Model Request - Add LightGBM

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/parsnip#370]
It looks like Microsoft is getting close to CRAN acceptance of their `LightGBM`. It's a powerful algorithm that has just played a big part in winning solutions to the recent M5 Forecasting Competition (Kaggle). Definitely a good one to add to `parsnip` or a `parsnip`-adjacent library. Any thoughts?

Reference: microsoft/LightGBM#3338

**Comment by mdancho84** [comment]
Just found out about this: curso-r/treesnip

**Comment by zenggyu** [comment]
@topepo @Athospd @dfalbel, why not just merge the part of treesnip that's associated with lightgbm into parsnip?  Given its popularity and amazing performance, I think lightgbm deserves a place in parsnip, just like xgboost.

**Comment by topepo** [comment]
Because of the non-R-ness of their interface, that model needs a wrapper function. As a consequence of that, it would need to be a formal dependency. I want to avoid more of those, especially for packages where it is a pain to get installed (like this one). It might be better once they are on CRAN but I think that it is fine to be an a separate package.

**Comment by jameslamb** [comment]
I found this discussion via GitHub search. I'd like to inform everyone here that `{lightgbm}` is now on CRAN 😀 

https://CRAN.R-project.org/package=lightgbm

> the non-R-ness of their interface

If this refers to LightGBM, I'd appreciate if someone working on `{parsnip}` or interested in seeing a `{lightgbm}` integration with it would [open an issue in LightGBM](https://github.com/microsoft/LightGBM/issues) explaining what you'd like to see added or changed.
