### ISSUE TITLE
Feature Request: set ranger num.threads to function default

### ISSUE THREAD

**Issue by markfairbanks** [tidymodels/parsnip#430]
I was using parsnip and noticed that ranger seemed to run slower with tidymodels. Turns out it was due to the fact that parsnip sets `num.threads = 1` in ranger.

``` r
library(parsnip)

rand_forest() %>%
  set_mode("regression") %>%
  set_engine("ranger") %>%
  translate()
#> Random Forest Model Specification (regression)
#> 
#> Computational engine: ranger 
#> 
#> Model fit template:
#> ranger::ranger(x = missing_arg(), y = missing_arg(), case.weights = missing_arg(), 
#>     num.threads = 1, verbose = FALSE, seed = sample.int(10^5, 
#>         1))
```

From the documentation for `ranger::ranger()`:

> num.threads Number of threads. Default is number of CPUs available.

Is it possible to get this set as the default for parsnip? Or is there a reason why 1 was selected?

**Comment by juliasilge** [comment]
The reason we set this as a default is because we prioritize [parallelization at the **resample** level](https://www.tmwr.org/resampling.html), in which case you want each model to train on one worker/thread. If in your case you are not using resampled data, you can set `num.threads` as an engine argument:

``` r
library(parsnip)

rand_forest() %>%
  set_mode("regression") %>%
  set_engine("ranger", num.threads = 4) %>%
  translate()
#> Random Forest Model Specification (regression)
#> 
#> Engine-Specific Arguments:
#>   num.threads = 4
#> 
#> Computational engine: ranger 
#> 
#> Model fit template:
#> ranger::ranger(x = missing_arg(), y = missing_arg(), case.weights = missing_arg(), 
#>     num.threads = 4, verbose = FALSE, seed = sample.int(10^5, 
#>         1))
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by markfairbanks** [comment]
Gotcha, makes sense. I figured there might be a reason. I can just keep setting it as necessary.

Thanks
