### ISSUE TITLE
`set_engine(object, engine)` should be `set_engine(object, engine = NULL)`

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/parsnip#494]
Since if `engine = NULL` we choose a default for the user with a message
https://github.com/tidymodels/parsnip/pull/488/files

It is better if this is explicit in the function signature, and documented in the help file.

Possibly also `set_mode(object, mode = NULL)`?

**Comment by juliasilge** [comment]
We don't currently have checking + choosing a default like this:
https://github.com/tidymodels/parsnip/blob/6d6b0a7b01eeedca0420f0acbb57cd628c6c4312/R/engines.R#L16
for mode because it doesn't make sense for all models, and it's tough to be able to tell at that point.

We currently throw a warning if we choose a default for engine, which feels strange to me if `NULL` is explicit in the function signature and what it does is documented. Should that be deescalated to a message?

**Comment by DavisVaughan** [comment]
It's odd because it looks like we tried to do something similar with mode here:
https://github.com/tidymodels/parsnip/blob/a546656d024d099cae0cceec1938e3a84cff8209/R/arguments.R#L79-L81

But then we abort on null modes here
https://github.com/tidymodels/parsnip/blob/6d6b0a7b01eeedca0420f0acbb57cd628c6c4312/R/aaa_models.R#L146
