### ISSUE TITLE
svm margin

### ISSUE THREAD

**Issue by Steviey** [tidymodels/parsnip#539]
Is it calles margin or svm_margin? And is it tuneable?

`unused argument (svm_margin = tune())

Error in UseMethod("margin") : 
  no applicable method for 'margin' applied to an object of class "NULL"`

**Comment by juliasilge** [comment]
This parameter in tidymodels for SVMs is called `margin`. You can find [this info in the documentation](https://parsnip.tidymodels.org/reference/svm_rbf.html).

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
data(bivariate)

biv_folds <- vfold_cv(bivariate_train, v = 3, strata = Class)

biv_rec <-
  recipe(Class ~ ., data = bivariate_train) %>%
  step_BoxCox(all_predictors())%>%
  step_normalize(all_predictors())

svm_spec <-
  svm_rbf(margin = tune()) %>%
  set_mode("classification") %>%
  set_engine("kernlab")

svm_wf <- workflow(biv_rec, svm_spec)

tune_grid(svm_wf, biv_folds, grid = 7)
#> # Tuning results
#> # 3-fold cross-validation using stratification 
#> # A tibble: 3 x 4
#>   splits            id    .metrics          .notes          
#>   <list>            <chr> <list>            <list>          
#> 1 <split [672/337]> Fold1 <tibble [14 × 5]> <tibble [0 × 1]>
#> 2 <split [673/336]> Fold2 <tibble [14 × 5]> <tibble [0 × 1]>
#> 3 <split [673/336]> Fold3 <tibble [14 × 5]> <tibble [0 × 1]>
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) demonstrating the problem you experienced? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by juliasilge** [comment]
Let us know if you have further questions!
