### ISSUE TITLE
parsnip should raise an error when users use logistic_reg() for multiclass classification

### ISSUE THREAD

**Issue by zenggyu** [tidymodels/parsnip#545]
Currently parsnip does not throw an error if a user chooses `logistic_reg()` to fit a multiclass classification model, but the result is wrong and misleading. Moreover, the documentation doesn't mention that `logistic_reg()` should only be used for binary classification. It took me a while to figure out that I should use `multinom_reg()` instead. It would be nice if parsnip can prevent this usage explicitly.

``` r
library(parsnip)
fit <- logistic_reg() %>%
  set_mode("classification") %>%
  set_engine("glm") %>%
  fit(Species ~ ., data = iris)
#> Warning: glm.fit: algorithm did not converge
#> Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
predict(fit, new_data = iris)
#> # A tibble: 150 x 1
#>    .pred_class
#>    <fct>      
#>  1 setosa     
#>  2 setosa     
#>  3 setosa     
#>  4 setosa     
#>  5 setosa     
#>  6 setosa     
#>  7 setosa     
#>  8 setosa     
#>  9 setosa     
#> 10 setosa     
#> # … with 140 more rows
```

<sup>Created on 2021-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by juliasilge** [comment]
We recently revamped our documentation so that `logistic_reg()` says:

> `logistic_reg()` defines a generalized linear model for binary outcomes. A linear combination of the predictors is used to model the log odds of an event.

We are already highlighting that it is for binary outcomes but we could add a pointer to `multinom_reg()` on that landing page. 

Sidenote: Should we also mention that some engines like xgboost and ranger handle multiclass classification on their own? Probably not here.

In [`translate.logistic_reg`](https://github.com/tidymodels/parsnip/blob/2c2dc5c1bd60e14a73fe8a4b19953a18f30179ad/R/logistic_reg.R#L79) we could check for a two-factor outcome.
