### ISSUE TITLE
Random forest with  block bootstrap

### ISSUE THREAD

**Issue by Shafi2016** [tidymodels/parsnip#617]
Hello, I am using Random forest with the ranger. I have a question regarding the bootstrap implement of a ranger with parsnip. Is it using block bootstrap to subsample time series in ranger with parsnip.? If it not is there an easy way to do so with parsnip

```
model_spec_rf_tune <- rand_forest(
  mode    = "regression",
  mtry    = tune(),
  trees   = tune(),
  min_n   = tune(),
 
) %>% 
  set_engine("ranger")
```

**Comment by juliasilge** [comment]
I'm a bit fuzzy on your question here, but here are a few ideas that may help you:

- If you are familiar with ranger and want to know what type of ranger call you are setting up with your tidymodels code, you can use `translate()`:

``` r
library(parsnip)

model_spec_rf_tune <- 
  rand_forest(
    mode    = "regression",
    mtry    = tune(),
    trees   = tune(),
    min_n   = tune(),
  ) %>% 
  set_engine("ranger")

model_spec_rf_tune %>% translate()
#> Random Forest Model Specification (regression)
#> 
#> Main Arguments:
#>   mtry = tune()
#>   trees = tune()
#>   min_n = tune()
#> 
#> Computational engine: ranger 
#> 
#> Model fit template:
#> ranger::ranger(x = missing_arg(), y = missing_arg(), case.weights = missing_arg(), 
#>     mtry = min_cols(~tune(), x), num.trees = tune(), min.node.size = min_rows(~tune(), 
#>         x), num.threads = 1, verbose = FALSE, seed = sample.int(10^5, 
#>         1))
```

<sup>Created on 2021-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

- If you would like to learn more about resampling in tidymodels including bootstrapping, check out the [rsample](https://rsample.tidymodels.org/) package. There are time-based resampling methods [like `sliding_period()` and friends](https://rsample.tidymodels.org/reference/slide-resampling.html).

- The [timetk](https://business-science.github.io/timetk/) package has functions for time series cross-validation.

- This question seems to be more about modeling practice rather than reporting a bug or requesting a feature in software, so for questions like this in the future, we invite you to post on [RStudio Community](https://rstd.io/tidymodels-community) in the ML/modeling category rather than on GitHub.

**Comment by Shafi2016** [comment]
Thank you @juliasilge. I am familiar with timetk or resample packages. We use                                      
 ```
 resamples_fitted <- submodels_2_tbl %>% modeltime_fit_resamples(
  resamples = resamples_tscv ,
  control   = control_resamples(verbose = TRUE,
                                allow_par = TRUE,
                                save_pred = TRUE,
                                pkgs = "treesnip"))
```

However, I am looking for the possibility of something similar to this presentation (http://www.user2019.fr/static/pres/t257053.pdf ) on block boostraping for the time series data.

**Comment by topepo** [comment]
If you are asking about the internal bootstrap used by `ranger()`, it uses the standard bootstrap (as far as I can tell by reading `?ranger`).

**Comment by Shafi2016** [comment]
Thank you @topepo
