### ISSUE TITLE
question: could anyone explain the origin of the parsnip name?

### ISSUE THREAD

**Issue by ssh352** [tidymodels/parsnip#620]
rsample
tune
dials
are very intuitive but not parsnip.

**Comment by hfrick** [comment]
Max talks about the naming of parsnip right at the beginning of this talk 🥕 
https://www.rstudio.com/resources/rstudioconf-2019/parsnip-a-tidy-model-interface/

For general questions like this one, which are not reporting a bug or requesting a feature in software, we invite you to post on RStudio Community in the ML/modeling category rather than on GitHub.
