### ISSUE TITLE
SageMaker as backend

### ISSUE THREAD

**Issue by dietrichson** [tidymodels/parsnip#635]
@EmilHvitfeldt are you aware of any efforts to add SageMaker as a backend?

If so, we would love to contribute and if not we might coordinate to add these features as we will surely need them in the intermediate future.

**Comment by topepo** [comment]
SageMaker has their own build of xgboost and we probably won't add that as an engine to `boost_tree()`. 

If you are interested in running parsnip/tidymodels on SageMaker (even in parallel), that should be fine since it will just install inside of R as it would anywhere else. I believe that we are working on tools and docker builds that should make getting to that point a lot easier.
