### ISSUE TITLE
allow re-registration of same model information

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#653]
To avoid issues running `devtools::test()` and/or `load_all()`. 

The idea is to allow extension packages to (silently) overwrite the model registry environments  _if the same data is being registered_. 

If other data is trying to overwrite, we should issue and error saying

 - If you are working on a different extension package, we don't allow this
 -  Otherwise, do a hard restart of the R session (i.e. don't `load_all()`)

**Comment by hfrick** [comment]
material for context:

no `onUnload()` hooks called in `load_all()`:
https://github.com/r-lib/pkgload/blob/e43073ca71fd9e2c3a759f472568518e8801353d/R/load.r#L62-L66

because it can cause crashes for packages using compiled code: https://github.com/r-lib/pkgload/issues/148#issuecomment-790910702

PR introducing this behaviour: https://github.com/r-lib/pkgload/pull/133
