### ISSUE TITLE
FR: pam()

### ISSUE THREAD

**Issue by exsell-jc** [tidymodels/parsnip#710]
There is KNN in `parsnip` already: https://parsnip.tidymodels.org/reference/nearest_neighbor.html

PAM or medoid-based NN methods may be a bit more robust, but computationally more expensive. PAM is available in `cluster` package (`pam()`).

So there is PAM-lite: https://www.youtube.com/watch?v=gW5wOaBwjxg

Interestingly, `broom` already has some `pam()` handling (`aer-tidiers.R` and `pam-tidiers.R`): https://github.com/tidymodels/broom/tree/4a6cdcb78d8508236bc7ef1b47ae0e461b86d478/R

e.g. https://www.rdocumentation.org/packages/broom/versions/0.7.2/topics/tidy.pam

**Comment by EmilHvitfeldt** [comment]
Hello @exsell-jc 👋 

The `pam()` method is an unsupervised clustering method, and would thus not be a good fit for parsnip. We are working sister-package to parsnip here https://github.com/EmilHvitfeldt/celery which enables clustering, including using `pam()` (not yet implemented)

We are planning to add `pam` to celery, so I'll close this issue here. If you want you can add a similar issue in that repository to get updates once we add support for `pam`.
