### ISSUE TITLE
Do model specifications need to evaluate their arguments?

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/parsnip#84]

**Comment by topepo** [comment]
`translate` does need the evaluated environment in some cases:

```r
  # add checks to error trap or change things for this method
  if (x$engine == "ranger") {
    if (any(names(x$method$fit$args) == "importance"))
      if (is.logical(x$method$fit$args$importance))
        stop("`importance` should be a character value. See ?ranger::ranger.",
             call. = FALSE)
    # unless otherwise specified, classification models are probability forests
    if (x$mode == "classification" && !any(names(x$method$fit$args) == "probability"))
      x$method$fit$args$probability <- TRUE
  }
```

That doesn't mean that we can't program around that though.

**Comment by topepo** [comment]
If we go down this road, it makes more sense to use `...` instead of a list of extra arguments..

**Comment by topepo** [comment]
Let's say someone does

```r
mod_1 <- rand_forest(mtry = floor(sqrt(ncol(iris))))
```
the quosure captures
```
$mtry
<quosure>
  expr: ^floor(sqrt(ncol(iris)))
  env:  global
```
and `iris` is in the global environment.  

`make_call` wants to insert the expression into the fit call and will evaluate it in the environment that we've carried around so far (that contains the descriptors and training data). However, `iris` shouldn't be there (or at least isn't guaranteed to be). 

_If_ we follow this same process, we would just have to document that variables from the global environment shouldn't be used here.

_If we do something different_, we could have to evaluate this argument before inserting it into the call. However, that could insert a lot of stuff that we might want to avoid (like a `family` object) or it could fail if someone uses a data descriptor or a data object reference.  

I'm leaning towards the first option and extracting the expression as being the best (or least worse).

**Comment by topepo** [comment]
[Initial changes](https://github.com/topepo/parsnip/tree/no-initial-eval) to `rand_forest()` work and weren't that difficult to make. Examples of new syntax are:
```r
rand_forest(mtry = varying())
rand_forest(mtry = floor(.3 * ncol(data)), sample.fraction = .75, seed = 12)
rand_forest(mtry = floor(.3 * n_col), sample.fraction = .75, seed = 12)
rand_forest(keep.inbag = TRUE, probability = TRUE)
```

Minor concerns:

 * The previous interface with `others` clearly separated the main arguments from the extra ones. Using `...` is more convenient but eliminates that separation. It may be confusing as to why some arguments are renamed and others are not when they are exposed in the same way. 

 * It also might be confusing if someone uses a descriptor (e.g. `mtry = floor(n_col/2)`); when they read the call, it would be reasonable to think that `n_col` is in their global environment. Maybe renaming these in some way would make it more obvious (since `n_col` is pretty innocuous). Using functions (as previously suggested) might help this but adds different confusion in the same amounts.

**Comment by DavisVaughan** [comment]
I think a lot of R users are familiar with "`...` arguments are passed on to so and so underlying method" so I don't think it is that confusing to understand what it is doing. 

Does this make tuning over extra arguments easier at all? You can now do `sample.fraction = varying()` or something similar rather than it being in the list. Not sure if that helps you on the implementation side.

I do think `n_cols` is too innocuous. Maybe `.n_cols`. `ggplot2` does things like `..density..` if I remember right. I think a function would be fine too like `n_cols()` but I'm not sure how the implementation of that would work.

I'm still iffy on the fact that you won't be able to use any variables from the global env. That feels...off, and like a big potential source of user frustration, but I'm not sure what the solution is just yet.

**Comment by hadley** [comment]
Another option would be to evaluate everything, and requite the user to supply a function/formula for dynamic stuff:

```R
rand_forest(mtry = varying())
rand_forest(mtry = ~ floor(.3 * ncol(data)), sample.fraction = .75, seed = 12)
rand_forest(mtry = ~ floor(.3 * n_col), sample.fraction = .75, seed = 12)
rand_forest(keep.inbag = TRUE, probability = TRUE)
```

(In this scenario `varying()` would have to evaluate to a sentinel value)

This also strikes me as similar to ggvis. Could you imagine this working? (i.e. automatically generating a shiny app with slider)

```R
rand_forest(mtry = input_slider(0, 100))
```

**Comment by topepo** [comment]
@DavisVaughan 

> Does this make tuning over extra arguments easier at all? You can now do `sample.fraction = varying()` or something similar rather than it being in the list.

You could do this before. I think that it just saves on typing `others = list(`...

@hadley 

> Another option would be to evaluate everything

We avoid doing that so that functions and larger objects don't get embedded into the call (e.g. `family` and data objects).

> This also strikes me as similar to ggvis. Could you imagine this working? 

My first thought is that I want to separate the model tuning parts from the fitting parts. 

While `parsnip` does have `varying()`, it is only used as a placeholder. Going beyond that with `parsnip` proper raises the complexity significantly. We'd still have to identify which parameters have grid-like values, and setting definitive ranges on those would add more syntax and complexity. For model tuning, the current vision of the system has the process of:

1. Setup specification using a `parsnip` model spec
1. Identify tuning parameters
1. Match tuning parameters to templates in `dials`. 
1. Finalize the parameter ranges (where needed)
1. Choose a method to optimize (grid search, random search, iterative search....)
 
`parsnip` going beyond steps 1 and 2 widens the scope a lot.

**Comment by hadley** [comment]
Evaluating all arguments in the call to `rand_forest` is independent of whether or not you inline them in the call to the actual modelling function

Sounds like the ggvis stuff is more in the realm of dials. It would be nice to be able to automatically generating a shiny app that let you interactively explore the options (I see that as being most useful for teaching)
