### ISSUE TITLE
Export xy / formula conversion utilities

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/parsnip#86]
For the eventual dummy/demonstration package, I think we'll want to export

- `convert_xy_to_form_fit()`
- `convert_form_to_xy_fit()`

so that developer's don't have to think about that at all. We'll need to provide advice on how to get data into a consistent format both at `fit()` time and at `predict()` time.

**Comment by alexpghayes** [comment]
Effectively this is what `hardhat` will do, if I understand correctly. @DavisVaughan?

**Comment by DavisVaughan** [comment]
I suppose it may be able to help with formula -> xy, but `hardhat` has no infrastructure for going from xy -> formula. Since some engines like `lm()` only have the formula method, I think that infrastructure in parsnip will definitely still be required.

**Comment by alexpghayes** [comment]
Could this get moved to `hardhat` so the all the data input logic lives in one place? Or is there `parsnip` specific stuff in some of the transformations?

**Comment by DavisVaughan** [comment]
Since the main goal of `hardhat` is to help create new modeling packages, my gut reaction is that I don't think there is reason to have xy->formula infrastructure there. I don't think it would be useful for much outside of parsnip's requirements of constructing a formula to pass along to the underlying modeling function (which would then again probably convert that back into xy of some kind).

**Comment by juliasilge** [comment]
Closing this for now. We can revisit if this is appropriate/needed later in either hardhat or possibly here in parsnip.

Thanks so much all! 👏
