### ISSUE TITLE
In classification problems, merging `probably` package when determining best threshold.

### ISSUE THREAD

**Issue by SHo-JANG** [tidymodels/parsnip#986]
As far as I can understand, we're using `prob_to_class_2`  as the default option when predicting class. 
```r
prob_to_class_2 <- function(x, object) {
  x <- ifelse(x >= 0.5, object$lvl[2], object$lvl[1])
  unname(x)
}
```

However, in many cases, the threshold is not 0.5. (Especially in imbalanced datasets.)

 In this case, I wonder if we could use the `threshold_perf()` function in the `probably` package during the tuning process to check if the model is potentially classifying really well.

 I think it's a really necessary feature, what do you think?

**Comment by topepo** [comment]
It is an important feature. After the posit conference, we will be working on post-processing tools and this is one of them. 

We'll try to make it natural so that you can treat the threshold parameter like any other tuning parameter. If you use a workflow, it will also adjust the hard class predictions automatically (once you've picked a threshold).

**Comment by SHo-JANG** [comment]
Thank you so much for all the hard work you do to make the system more complete.

**Comment by SHo-JANG** [comment]
I think that hyperparameterizing to find the optimal threshold would be time consuming and could lead to overfitting.

Instead , I searched for a way to determine the optimal threshold. [related paper](https://www.sciencedirect.com/science/article/pii/S0304380008002275)


In Section 2.3. Threshold criteria, 
(6)PredPrev = Obs. 
This means that we want the class ratio of the predicted result to be equal to the ratio of the observed classes in the trained data, i.e., we use quantile(probs = 1- "Obs class ratio") from the predicted probability vector as the threshold. 

The code to implement this in the training process is as follows.
```r

prob_to_class_2_custom <- function(x, object) {
  obs_ratio<- object$fit$y |> mean()
  pred_equal_obs_threshold <- quantile(x,probs = 1-obs_ratio)
  x <- ifelse(x >= pred_equal_obs_threshold, object$lvl[2], object$lvl[1])
  unname(x)
}

```

I would like to use this function as the default option. 
However, it seems that I need to redefine the engine to apply this function. Is there any way to use this function in an existing engine?

**Comment by simonpcouch** [comment]
Long time no see😝 We've got some good news here, though—custom probability thresholds and other postprocessing functionality is now available via [tailor](https://github.com/tidymodels/tailor)s, which can be added to workflows in the dev version of the workflows package. You can read more on that work on [this blog post](https://www.tidyverse.org/blog/2024/10/postprocessing-preview/).

Since these changes will otherwise live on the tailor repo, I'm going to go ahead and close!
